[build]
rustflags = ["-Zlocation-detail=none", "-Zthreads=0", "-Ctarget-cpu=native"]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort", "optimize_for_size"]
